export const GET_WIDGETDATABYMODULE = 'GET_WIDGETDATABYMODULE';
export const GET_WIDGETDATA = 'GET_WIDGETDATA';
export const GET_TICKET = 'GET_TICKET';
export const GET_ENTRADA = 'GET_ENTRADA';
export const GET_SALIDA = 'GET_SALIDA';
export const GET_CUPON = 'GET_CUPON';
export const GET_COBRO = 'GET_COBRO';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_LOADINGMODULE = 'TOGGLE_LOADINGMODULE';
export const TOGGLE_LOADINGGRAPH = 'TOGGLE_LOADINGGRAPH';
export const GET_PRINCIPALGRAPH = 'GET_PRINCIPALGRAPH';
export const GET_PRINCIPAL_RANGE = 'GET_PRINCIPAL_RANGE'
export const GET_ERROR = 'GET_ERROR';

// AUTH
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

// MENU
export const GET_MENU = 'OBTENER_MENU';
export const MENU_SUCCESS = 'MENU_EXITOSO';
export const MENU_ERROR = 'MENU_ERROR';

// TOAST
export const SHOW_TOASTER = 'SHOW_TOASTER';